### ISSUE TITLE
force-seq-for-nested-keys

### ISSUE THREAD

**Issue by brettrowberry** [Wall-Brew-Co/clj-xml#10]
# Feature Request

## Problem Statement

This option exists today and does exactly what it's supposed to:
`force-seq?` - to coerce child XML nodes into an array of maps.

Sometimes, there will only ever be a single child XML node, but the edn returned will be a vector of maps instead of a single map.

## Ideal Solution

A new option, something like:
`force-seq-for-nested-keys` - to coerce child XML nodes using the supplied nested keys into an array of maps

### Alternative solutions

Workaround. 
When cli-xml sometimes returns a map and other times a vector of maps, we put the single map into a vector so we can consistently handle a vector of maps.

``` clojure
(defn vectorize
  [x]
  (if (vector? x)
    x
    [x]))
```

**Comment by nnichols** [comment]
An early cut of the implementation is here: https://github.com/Wall-Brew-Co/clj-xml/tree/wb-10-force-seq-for-nested-keys

I'm currently testing it

**Comment by jmhawk** [comment]
not sure how you feel about this @nnichols  but we could also add in a helper function to basically force the map to a seq inline. 
```
(defn coerce-map-to-seq-of-maps
  [base-input]
  (if (map? base-input)
    (map #(into {} [%]) base-input)
    base-map))
```

**Comment by nnichols** [comment]
@jmhawk The additional option wasn't too bad to implement

**Comment by nnichols** [comment]
Closed by: https://github.com/Wall-Brew-Co/clj-xml/pull/11
